# Generated by Django 5.1.4 on 2024-12-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, verbose_name='Tytul filmu')),
                ('plakat', models.ImageField(upload_to='', verbose_name='Plakat')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32, verbose_name='Nazwa sali')),
                ('liczba_miejsc', models.IntegerField(verbose_name='Liczba miejsc')),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.DateTimeField(verbose_name='Termin')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seanse.film')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seanse.sala')),
            ],
        ),
    ]
